<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.6rca7gt' shared service.

return $this->services['service_locator.6rca7gt'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('moduleRepository' => function () {
    $f = function (\App\Repository\ModuleRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\ModuleRepository']) ? $this->services['App\Repository\ModuleRepository'] : $this->load('getModuleRepositoryService.php')) && false ?: '_'});
}));
