<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3p9naxx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3p9naxx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3p9naxx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3p9naxx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container3p9naxx\srcDevDebugProjectContainer(array(
    'container.build_hash' => '3p9naxx',
    'container.build_id' => '7ae0f5a5',
    'container.build_time' => 1529412027,
), __DIR__.\DIRECTORY_SEPARATOR.'Container3p9naxx');
