<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX69mayx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX69mayx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX69mayx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX69mayx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerX69mayx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'X69mayx',
    'container.build_id' => 'bff12c2e',
    'container.build_time' => 1529419611,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX69mayx');
