<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6kr7idd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6kr7idd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6kr7idd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6kr7idd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container6kr7idd\srcDevDebugProjectContainer(array(
    'container.build_hash' => '6kr7idd',
    'container.build_id' => 'e3707578',
    'container.build_time' => 1529417747,
), __DIR__.\DIRECTORY_SEPARATOR.'Container6kr7idd');
