<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.hwuuob5' shared service.

return $this->services['service_locator.hwuuob5'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('sallesRepository' => function () {
    $f = function (\App\Repository\SallesRepository $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Repository\SallesRepository']) ? $this->services['App\Repository\SallesRepository'] : $this->load('getSallesRepositoryService.php')) && false ?: '_'});
}));
