security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User: plaintext
    providers:
        user_db:
            entity: { class: App\Entity\User, property: username }
    role_hierarchy:
        ROLE_USER:  ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user_db
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
              path: /logout
              target: /

    access_control:
          # { path: ^/admin/user_show, roles: ROLE_ADMIN }
         # { path: ^/profile, roles: ROLE_USER }
