home_page:
    path: /
    defaults:
      _controller: 'App\Controller\AppController::index'
module:
    path: /module
    defaults: {_controller: 'App\Controller\ModuleController'}
module_index:
    path: /module/
    defaults: {_controller: 'App\Controller\ModuleController::index'}
module_new:
    path: /module/new
    defaults: {_controller: 'App\Controller\ModuleController::new'}