# home_page:
#     path: /
#     defaults: 
#       _controller: 'App\Controller\AppController::index'

# salles_index:
#     path: /salles
#     defaults: { _controller: 'App\Controller\SallesController::index' }

