home_page:
    path: /
    defaults: 
      _controller: 'App\Controller\AppController::indexAction'
location_index:
    path: /locations
    defaults: 
      _controller: 'App\Controller\LocationController::index'
module:
    path: /module
    defaults: {_controller: 'App\Controller\ModuleController'}
module_index:
    path: /module/
    defaults: {_controller: 'App\Controller\ModuleController::index'}
module_new:
    path: /module/new
    defaults: {_controller: 'App\Controller\ModuleController::new'}
module_show:
    path: /module/{idModule}
    defaults: {_controller: 'App\Controller\ModuleController::show'}
module_edit:
    path: /module/{idModule}/edit
    defaults: {_controller: 'App\Controller\ModuleController::edit'}
